spring:
  config:
    activate:
      on-profile: local
  application:
    name: coupon-core
  datasource:
    url: jdbc:mariadb://leevelop.com:2906/modooagit
    driver-class-name: org.mariadb.jdbc.Driver
    username: merong2969
    password: Seung0075!
    hikari:
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-timeout: 3000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6380
---
spring:
  config:
    activate:
      on-profile: test
  application:
    name: coupon-core
  datasource:
    url: jdbc:mariadb://leevelop.com:2906/modooagit
    driver-class-name: org.mariadb.jdbc.Driver
    username: merong2969
    password: Seung0075!
    hikari:
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-timeout: 3000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6380
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://PROD_URL:3306/coupon?useUnicode=yes&characterEncoding=UTF-8&rewriteBatchedStatements=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-timeout: 3000
      username: PROD_USER_NAME
      password: PROD_PASSWORD
  jpa:
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: PROD_URL
      port: 6380
